# Matrices

In [4]:
M = zeros(3)

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

In [5]:
M = zeros(3, 3)

3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [6]:
M[1, 2]

0.0

In [7]:
M[1,2] = 10

10

In [8]:
M

3×3 Array{Float64,2}:
 0.0  10.0  0.0
 0.0   0.0  0.0
 0.0   0.0  0.0

In [9]:
using Plots

In [10]:
heatmap(M)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 1.0 
 
 
 1.5 
 
 
 2.0 
 
 
 2.5 
 
 
 3.0 
 
 
 1.0 
 
 
 1.5 
 
 
 2.0 
 
 
 2.5 
 
 
 3.0 
 
 
<image width="505" height="381" xlink:href="data:;base64,
iVBORw0KGgoAAAANSUhEUgAAAfkAAAF9CAYAAAAHlxEqAAAGJ0lEQVR4nO3XwQmAMAAEwSgp1NIs
VNAKxJcElpkK7rfcNsa8BwCQs68eAAD8Q+QBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK
5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErk
ASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQB
IErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEg
SuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK
5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErk
ASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQB
IErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEg
SuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK
5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErk
ASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQB
IErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEg
SuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK
5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErk
ASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQB
IErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEg
SuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK
5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErkASBK5AEgSuQBIErk
ASBK5AEgaq4eAF+u+1w9AV7N7Vg9AV558gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXy
ABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIA
ECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQ
JfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl
8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXy
ABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIA
ECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQ
JfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl
8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXy
ABAl8gAQJfIAECXyABD1AFrzBv8iPJMyAAAAAElFTkSuQmCC
" transform="translate(30, 3)"/>

In [11]:
M = [1 2 0
     1 2 1
     2 2 0]

3×3 Array{Int64,2}:
 1  2  0
 1  2  1
 2  2  0

In [13]:
heatmap(M)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 1.0 
 
 
 1.5 
 
 
 2.0 
 
 
 2.5 
 
 
 3.0 
 
 
 1.0 
 
 
 1.5 
 
 
 2.0 
 
 
 2.5 
 
 
 3.0 
 
 
<image width="505" height="381" xlink:href="data:;base64,
iVBORw0KGgoAAAANSUhEUgAAAfkAAAF9CAYAAAAHlxEqAAAGRUlEQVR4nO3XsQ1BYQCFUeTtRKtQ
iw0Mpxe1QstOEiZ4Con88eWcCW735S6fr9NrAcBXpuVx9ASYtRo9AAD4DZEHgCiRB4AokQeAKJEH
gCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeA
KJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4Ao
kQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiR
B4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEH
gCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeA
KJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4Ao
kQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiR
B4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEH
gCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4Co6ba5jN4AH23v+9ETYNZ1fRg9AWZ58gAQJfIA
ECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQ
JfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl
8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXy
ABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIA
ECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQ
JfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl
8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXy
ABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIA
ECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABAl8gAQJfIAECXyABA1jR4A8M92j/PoCTDLkweA
KJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4Ao
kQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiR
B4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEH
gCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeA
KJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4Ao
kQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiR
B4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEH
gCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeA
KJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4AokQeAKJEHgCiRB4CoN1SVDQHtlnbfAAAA
AElFTkSuQmCC
" transform="translate(30, 3)"/>

## Derivada

In [14]:
dif_finita(f, a, h) = (f(a+h)-f(a)) / h 

dif_finita (generic function with 1 method)

In [15]:
derivada(f, a) = dif_finita(f, a, 1e-8)

derivada (generic function with 1 method)

In [16]:
derivada(x->x^2 - 3, 10)

20.00000165480742

## Color map

In [21]:
cgrad(:rainbow).colors

5-element Array{ColorTypes.RGBA{Float64},1}:
 RGBA{Float64}(0.501961,0.0,0.501961,1.0)
 RGBA{Float64}(0.0,0.0,1.0,1.0)          
 RGBA{Float64}(0.0,0.501961,0.0,1.0)     
 RGBA{Float64}(1.0,0.647059,0.0,1.0)     
 RGBA{Float64}(1.0,0.0,0.0,1.0)          

In [31]:
plot(M, alpha=2, color_palette=cgrad(:blues).colors)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 1.0 
 
 
 1.5 
 
 
 2.0 
 
 
 2.5 
 
 
 3.0 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 1.5 
 
 
 2.0 
 
 
 
 
 
 
 
 
 y1 
 
 
 
 y2 
 
 
 
 y3

In [33]:
M = rand(10, 10)
heatmap(M, color_palette=cgrad(:blues).colors)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 2.5 
 
 
 5.0 
 
 
 7.5 
 
 
 10.0 
 
 
 2.5 
 
 
 5.0 
 
 
 7.5 
 
 
 10.0 
 
 
<image width="496" height="381" xlink:href="data:;base64,
iVBORw0KGgoAAAANSUhEUgAAAfAAAAF9CAYAAAD7gjrgAAAJF0lEQVR4nO3X38vfZR3H8ft2C5dT
tFZqRk3zR1FNS5JcoimrGUQ/ILQDwxMpiIiwOo5gR1EUVBQIYTkCDxZ5EpRhIGR2kJahM8KJZbvv
MVHMZji327u/IT4XXDy3x+MveH3h4vP8vldPPHDp5sopYP+Xb5w9YYjbn7hp9oTFnvrEXbMnDPG+
+5+ZPWGxj2375OwJQ6yffHn2hCE+v3PL7AmLHTu5dfaEIfYd/tPsCYudMXsAAPD/E3AACBJwAAgS
cAAIEnAACBJwAAgScAAIEnAACBJwAAgScAAIEnAACBJwAAgScAAIEnAACBJwAAgScAAIEnAACBJw
AAgScAAIEnAACBJwAAgScAAIEnAACBJwAAgScAAIEnAACBJwAAgScAAIEnAACBJwAAgScAAIEnAA
CBJwAAgScAAIEnAACBJwAAgScAAIEnAACNp6csdbZm8YYse2V2ZPGOK1B/fNnrDYpV/dmD1hiE//
/lOzJyz22UtemD1hiH+9fPbsCUPc+vCO2RMW+9au/8yeMMSe1+2ePWExFzgABAk4AAQJOAAECTgA
BAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAE
CTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJ
OAAECTgABAk4AAQJOAAECTgABK3+bvdnNmePGGHXew7OnjDEdfe+a/aExV7cPDJ7whCH71ufPWGx
oz89b/aEIc75wZ7ZE4b4w83Pzp6w2G1PHJo9YYg7z7929oTFXOAAECTgABAk4AAQJOAAECTgABAk
4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTg
ABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAA
ECTgABAk4AAQJOAAELT654/s3Zw9YoSDRy6aPWGID17299kTFtt4bcvsCUNs2/bK7AmLHfrn22dP
GOK87cdmTxji109fNnvCYg89N3vBGA+euH/2hMVc4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQ
JOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk
4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTg
ABAk4AAQtPUdu/42e8MQ6y++YfaEIe559OrZExb7+QvPzJ4wxN1X7Zg9YbFrfrF99oQhbrz81Pgd
e9/Yv5nuferV2ROG+Mn1e2ZPWKz/mgDgNCTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQ
JOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk
4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAELT6
0vN3bs4eMcKZd981e8IQRx955+wJiz188L2zJwzx9UNHZk9Y7MKNt86eMMR9tzwye8IQnzuwe/aE
xfZeuGX2hCEeem519oTFXOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTg
ABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAA
ECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAELT65Mc/vDl7
xAgXXHx49oQh3vTj9dkTFvvLR6+dPWGId3/xr7MnLLbx9LHZE4Y4vrZj9oQhLvrh9tkTFvvuxTfM
njDElRf0v7UucAAIEnAACBJwAAgScAAIEnAACBJwAAgScAAIEnAACBJwAAgScAAIEnAACBJwAAgS
cAAIEnAACBJwAAgScAAIEnAACBJwAAgScAAIEnAACBJwAAgScAAIEnAACBJwAAgScAAIEnAACBJw
AAgScAAIEnAACBJwAAgScAAIEnAACBJwAAgScAAIEnAACBJwAAgScAAIWj3+x/dvzh4xwvM/2pg9
YYgv/PL62RMW23XuqfG/8PxtJ2ZPWOyOR988e8IQR29/YPaEIXZ+aW32hMX+feDM2ROGOPeaf8ye
sNip8aUFgNOMgANAkIADQJCAA0CQgANAkIADQJCAA0CQgANAkIADQJCAA0CQgANAkIADQJCAA0CQ
gANAkIADQJCAA0CQgANAkIADQJCAA0CQgANAkIADQJCAA0CQgANAkIADQJCAA0CQgANAkIADQJCA
A0CQgANAkIADQJCAA0CQgANAkIADQJCAA0CQgANAkIADQJCAA0DQ6nVn3bE5e8QIa2eszZ4wxPqr
j8+esNhLvz1r9oQhXn9T/009dvMHZk8Y4pLvnz17whC3Xb1z9oTF9n3oydkThnh87W2zJyzmAgeA
IAEHgCABB4AgAQeAIAEHgCABB4AgAQeAIAEHgCABB4AgAQeAIAEHgCABB4AgAQeAIAEHgCABB4Ag
AQeAIAEHgCABB4AgAQeAIAEHgCABB4AgAQeAIAEHgCABB4AgAQeAIAEHgCABB4AgAQeAIAEHgCAB
B4AgAQeAIAEHgCABB4AgAQeAIAEHgCABB4AgAQeAoK2/+cqvZm8Y4hs/u3X2hCG++djlsycsdvzb
B2ZPGOK/x78ze8Jy3/va7AVD3HDlLbMnDHHVOf2baec9/W/UysrKyhX798+esFj/NQHAaUjAASBI
wAEgSMABIEjAASBIwAEgSMABIEjAASBIwAEgSMABIEjAASBIwAEgSMABIEjAASBIwAEgSMABIEjA
ASBIwAEgSMABIEjAASBIwAEgSMABIEjAASBIwAEgSMABIEjAASBIwAEgSMABIEjAASBIwAEgSMAB
IEjAASBIwAEgSMABIEjAASBIwAEgSMABIOh/9GWequLlZkMAAAAASUVORK5CYII=
" transform="translate(39, 3)"/>

In [35]:
grad = ColorGradient(:blues)

PlotUtils.ColorGradient(ColorTypes.RGBA{Float64}[RGBA{Float64}(0.678431,0.847059,0.901961,1.0),RGBA{Float64}(0.0,0.0,0.545098,1.0)],[0.0,1.0])

In [37]:
heatmap(M, c = grad)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 2.5 
 
 
 5.0 
 
 
 7.5 
 
 
 10.0 
 
 
 2.5 
 
 
 5.0 
 
 
 7.5 
 
 
 10.0 
 
 
<image width="496" height="381" xlink:href="data:;base64,
iVBORw0KGgoAAAANSUhEUgAAAfAAAAF9CAYAAAD7gjrgAAAJDElEQVR4nO3X38uYZR3H8Z7xtOG2
x6mzLX+xNX/kVCzMTDqwRpAVhggdibAghKLDkh0UdNAQooN+GERYBwV21EEQYUSGSK2oVejB0Exp
ampjpgu3mZOe/oj7gov30+v1F3xuLrjffFcu3fu99bdtAJ+455rZE4b4/uGjsycs9rG7N8Zb3POF
986esNjxp16bPWGIrdvfPnvCEMeOnpg9YbHVzZtmTxji/Qcunz1hsY3xEgDwf0bAASBIwAEgSMAB
IEjAASBIwAEgSMABIEjAASBIwAEgSMABIEjAASBIwAEgSMABIEjAASBIwAEgSMABIEjAASBIwAEg
SMABIEjAASBIwAEgSMABIEjAASBIwAEgSMABIEjAASBIwAEgSMABIEjAASBIwAEgSMABIEjAASBI
wAEgSMABIEjAASBIwAEgSMABIEjAASBo9c3/vDV7wxBnz2yM77hkz9rsCYs9ceTl2ROGeOb2f82e
sNjTj5+cPWGI7RdsmT1hiB99/S+zJyz2+ftvnT1hiBee/ffsCYu5wAEgSMABIEjAASBIwAEgSMAB
IEjAASBIwAEgSMABIEjAASBIwAEgSMABIEjAASBIwAEgSMABIEjAASBIwAEgSMABIEjAASBIwAEg
SMABIEjAASBIwAEgSMABIEjAASBIwAEgSMABIEjAASBIwAEgSMABIEjAASBIwAEgSMABIEjAASBI
wAEgSMABIEjAASBIwAEgaPXAXVfO3jDE8SdfnT1hiC8/eGD2hMW2nLc6e8IQXzn4q9kTFrv6xotn
Txji9798bvaEIe6697rZExa74ZbdsycM8fhvX5o9YTEXOAAECTgABAk4AAQJOAAECTgABAk4AAQJ
OAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4
AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgA
BAk4AAQJOAAErXzy0z9bnz1ihJ3v3DZ7whD/ePbU7AmLbdq0MnvCEOfO/Xf2hMV27t46e8IQb5x5
a/aEIfbuv3D2hMUu3bM2e8IQl+07f/aExVzgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQ
JOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk
4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTg
ABC0+s8XTs/eMMT2HVtmTxjihg/snj1hsavfc/HsCUM88pNnZk9Y7OGHnpo9YYjDD3109oQhnv/b
qdkTFvvqvb+ePWGIg4dumj1hMRc4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4
AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgA
BAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAQJOAAECTgABAk4AAStnLft
m+uzR4yw7/qLZk8YYtdl22ZPWOyKq3bMnjDEBz++Z/aExc6ePjd7whA/ffDY7AlD3HHw2tkTFnvu
6ddmTxjikj3nz56wmAscAIIEHACCBBwAggQcAIIEHACCBBwAggQcAIIEHACCBBwAggQcAIIEHACC
BBwAggQcAIIEHACCBBwAggQcAIIEHACCBBwAggQcAIIEHACCBBwAggQcAIIEHACCBBwAggQcAIIE
HACCBBwAggQcAIIEHACCBBwAggQcAIIEHACCBBwAggQcAIIEHACCBBwAggQcAIJWP3Tnu2ZvGOLU
K2/MnjDE5w7fOnvCYj/82p9mTxji/s8+OnvCYms7Ns+eMMTWtY3xHbuv2D57wmJ/feLk7AlD/OGR
52dPWMwFDgBBAg4AQQIOAEECDgBBAg4AQQIOAEECDgBBAg4AQQIOAEECDgBBAg4AQQIOAEECDgBB
Ag4AQQIOAEECDgBBAg4AQQIOAEECDgBBAg4AQQIOAEECDgBBAg4AQQIOAEECDgBBAg4AQQIOAEEC
DgBBAg4AQQIOAEECDgBBAg4AQQIOAEECDgBBAg4AQQIOAEECDgBBK7su/+767BEj7L/pHbMnDHH7
3dfMnrDYKy+fmT1hiLOvn5s9YbEfHD46e8IQt925d/aEIY798cTsCYvtffeFsycMceLF07MnLOYC
B4AgAQeAIAEHgCABB4AgAQeAIAEHgCABB4AgAQeAIAEHgCABB4AgAQeAIAEHgCABB4AgAQeAIAEH
gCABB4AgAQeAIAEHgCABB4AgAQeAIAEHgCABB4AgAQeAIAEHgCABB4AgAQeAIAEHgCABB4AgAQeA
IAEHgCABB4AgAQeAIAEHgCABB4AgAQeAIAEHgCABB4Cg1UPfuW32hiG2rm2ePWGItQv63/HAoSOz
JwzxrZ/fMXvCYn9/8tXZE4Y48ovjsycMcd+3+//bIw9vjLe46sadsycs5gIHgCABB4AgAQeAIAEH
gCABB4AgAQeAIAEHgCABB4AgAQeAIAEHgCABB4AgAQeAIAEHgCABB4AgAQeAIAEHgCABB4AgAQeA
IAEHgCABB4AgAQeAIAEHgCABB4AgAQeAIAEHgCABB4AgAQeAIAEHgCABB4AgAQeAIAEHgCABB4Ag
AQeAIAEHgCABB4AgAQeAIAEHgKCV9334x+uzR4zwkU9dOXvCEA8c+t3sCYtdf8uu2ROG+PNjL86e
sNh1N2+Mt/jMl26ePWGIky+dmT1hsW988TezJwyxb/9Fsycs5gIHgCABB4AgAQeAIAEHgCABB4Ag
AQeAIAEHgCABB4AgAQeAIAEHgCABB4AgAQeAIAEHgCABB4AgAQeAIAEHgCABB4AgAQeAIAEHgCAB
B4AgAQeAIAEHgCABB4AgAQeAIAEHgCABB4AgAQeAIAEHgCABB4AgAQeAIAEHgCABB4AgAQeAIAEH
gCABB4AgAQeAIAEHgKD/AZHtkZz6qJfXAAAAAElFTkSuQmCC
" transform="translate(39, 3)"/>