# Muestra de una buena tarea 01

Hay muchas maneras de resolver el mismo problema. Aquí mostramos una buena serie de soluciones con código legible y ordenado.

## Repaso del notebook 01

#### [0] 
(i) Define una función `vol_esfera` que acepta un radio y calcula el volumen de la esfera con ese radio.
(ii) Utiliza tu función para calcular el volumen de la esfera con radio $\rho = 10$.

In [1]:
# Los comentarios pueden estar en líneas previamente vacías, como esta, si así es más claro.

vol_esfera(ρ) = (4π/3)*ρ^3  # También pueden ir aquí, si son comentarios más cortos.

vol_esfera (generic function with 1 method)

In [2]:
radio = 10  # Siempre nombra a tus variables antes de utilizarlas.
vol_esfera(radio)

4188.790204786391

(iii) Define una función `vol_cilindro` que calcula el volumen de un cilindro de radio $\rho$ y altura $\zeta$. 

(iv) Calcula el volumen del cilindro con radio $\rho = \frac{1}{2}$ y altura $\zeta = 10$. 

In [3]:
# Definir funciones con esta sintaxis sólo es recomendable cuando la definición es muy corta.

vol_cilindro(ρ,ζ) = π*ζ*ρ^2 

vol_cilindro (generic function with 1 method)

In [4]:
ρ = 1/2 
ζ = 10   
vol_cilindro(ρ, ζ)

7.853981633974483

# Creando datos y graficación

Una de las tareas fundamentales del cómputo científico es el manejar **datos** de todo tipo: leerlos de un archivo, o crearlos en una simulación; escribirlos a un archivo; visualizarlos, para extraer su mensaje; etc.

En este notebook veremos una forma rápida de crear datos y almacenarlos.

## Arreglos por comprensión

Tendremos que almacenar datos en algún lado. En Julia los almacenamos en arreglos.

Un **arreglo** es un vector, o una lista, o una secuencia, o un conjunto (ordenado) de datos. Se puede visualizar como una pichonera con cajitas consecutivas, en las cuales se guardan los taos.

Julia tiene una sintaxis poderosa para crear arreglos: **arreglos por comprensión**

En matemáticas, hay una notación bonita para especifar conjuntos. Por ejemplo, el conjunto de los cuadrados de los primeros diez enteros se escribe como sigue. Si notamos por $A := \{ 1, 2, \ldots, 10 \}$ los números de 1 a 10, entonces el conjunto $C$ de sus cuadrados es 

$$C := \{ x^2 : x \in A \}$$

En Julia, ¡podemos escribir algo similar! 

Primero, agarremos los números de 1 al 10:

In [5]:
A = 1:10

1:10

[1] ¿Qué **tipo de objeto** es esto? 

In [6]:
println("Este objeto es de tipo: ", typeof(A))

Este objeto es de tipo: UnitRange{Int64}


In [7]:
C = [i^2 for i in A]  # i^2 para i que recorre todos los valores en A

10-element Array{Int64,1}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

[2] ¿Qué tipo de objeto es este resultado? 

In [8]:
println("Este objeto es de tipo: ", typeof(C))

Este objeto es de tipo: Array{Int64,1}


Podemos leer esto como "el arreglo de $x^2$ *para* ('for') $x$ en el conjunto `A`", o "la colección [ordenada] de los cuadrados de los elementos de `A`.

[3] ¿Funciona si pones directamente `1:10` en lugar de `A`?

In [9]:
C = [i^2 for i in 1:10] #Sí funciona.

10-element Array{Int64,1}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

[4] (i) Utiliza la función `sum` para calcular la suma de estos cuadrados.

In [10]:
?sum # Es muy útil leer la documentación de las funciones predefinidas de Julia.

search: sum sum! sumabs summary sumabs2 sumabs! sum_kbn sumabs2! cumsum cumsum!



```
sum(itr)
```

Returns the sum of all elements in a collection.

```
sum(A, dims)
```

Sum elements of an array over the given dimensions.

```
sum(f, itr)
```

Sum the results of calling function `f` on each element of `itr`.


In [11]:
sum(C)

385

(ii) Escribe una función que calcule la suma de los primeros $N$ enteros. Verifica que siempre dé el resultado analítico conocido. (Es decir, hazlo para distintos $N$ y checa si sí sea cierto.)

In [12]:
# Un nombre descriptivo en las funciones ayuda a leer el código posteriormente. ¡Es por tu bien!

function suma_primeros_naturales(N) # Puedes utilizar el guión bajo para separar nombres largos.
    sum(1:N)
end

function suma_Gauss(N) # Evita nombres demasiado largos si al hacerlo no pierdes claridad.
    N*(N+1)/2
end

suma_Gauss (generic function with 1 method)

In [13]:
[suma_primeros_naturales(n) == suma_Gauss(n) for n in 1000:1000:10000] # Lo compruebo usando lo que ya aprendí.

10-element Array{Bool,1}:
 true
 true
 true
 true
 true
 true
 true
 true
 true
 true

Nótese que desde Julia 0.5, podemos poner un `if` al final de la comprensión para incluir sólo ciertos valores que satisfagan cierta condición, e.g.

In [14]:
[i for i in A if i%3 != 0]  # % es módulo;  != es "no es igual a"

7-element Array{Int64,1}:
  1
  2
  4
  5
  7
  8
 10

# Graficación

[5] (i) Da una lista de los números de 1 al 100 que sean múltiplos de 3 o 5. ["O" se escribe como `||`.] 

(ii) Checa a ojo que esté correcto. 

In [15]:
# Utiliza espacios cuando ayude a leer tu código.
# i%3 == 0 || i%5 == 0 vs i%3==0||i%5==0

lista_multiplos = [i for i in 1:100 if i%3 == 0 || i%5 == 0]

47-element Array{Int64,1}:
   3
   5
   6
   9
  10
  12
  15
  18
  20
  21
  24
  25
  27
   ⋮
  78
  80
  81
  84
  85
  87
  90
  93
  95
  96
  99
 100

(iii) Calcula su suma. ¿Cómo puedes verificar que la suma esté bien? Hazlo.

In [16]:
sum(lista_multiplos)

2418

In [17]:
#Hay varias maneras de verificarlo. Puedes elegir la que prefieras pero... ¡no ignores la pregunta!

# En el rango 1:100 hay: 33 múltiplos de 3, 20 múltiplos de 5 y 6 múltiplos de 15.
# Hay que tomar en cuenta que si sumamos los múltiplos del 3 y del 5, contamos doble los múltiplos de 15.

3*suma_Gauss(33) + 5*suma_Gauss(20) - 15*suma_Gauss(6)

2418.0

Ahora que somos capaces de producir datos interesantes, se nos antoja *visualizarlos*, es decir, graficarlos.

Hay varios paquetes gráficos en Julia. El paquete `Plots` provee una interfaz común a muchos de ellos.

Para utilizarlo, es necesario primero *instalar* el paquete; esto se hace una sola vez en cada instalación de Julia:

In [18]:
#Pkg.add("Plots") 

Recomendamos el "backend" GR:

In [19]:
#Pkg.add("GR")

El paquete se tiene que cargar *en cada sesión*:

In [20]:
using Plots  # "using" == "usando"
gr()   # escoger el "backend" GR

Plots.GRBackend()

El comando `using Plots` carga las funciones definidas en la librería para este notebook (que ya instalaste una vez con `Pkg.add`), para que ya se puedan utilizar.

[6] (i) Crea un arreglo `x` con números igualmente espaciados de -3 a 3 y un paso chiquito.

(ii) Crea un arreglo `y` que corresponde a la función $3x^2 - 2$.

(iii) Usa la función `plot` de `Plots` para graficar la función.

(iv) Utiliza la ayuda de la función [`?plot` o `help(plot)`] y en la documentación del paquete u otro lado para cambiar el estilo de la gráfica para utilizar líneas rojas y puntos verdes.

(v) Busca cómo agregar etiquetas a los ejes (lo cual debe hacerse en *cualquier* gráfica) y un título global, así como una leyenda.

In [21]:
?plot

search: plot plot! plotly plot3d Plots plot3d! plotlyjs plotarea plot_color



The main plot command.  Use `plot` to create a new plot object, and `plot!` to add to an existing one:

```
    plot(args...; kw...)                  # creates a new plot window, and sets it to be the current
    plot!(args...; kw...)                 # adds to the `current`
    plot!(plotobj, args...; kw...)        # adds to the plot `plotobj`
```

There are lots of ways to pass in data, and lots of keyword arguments... just try it and it will likely work as expected. When you pass in matrices, it splits by columns.  See the documentation for more info.


In [22]:
# Si todos los incisos se refieren a la misma gráfica los puedes hacer en una celda.

x = collect(-3:0.1:3) # collect() convierte el rango a un arreglo.
y = [3X^2 - 2 for X in x]
plot(x,y, linecolor=:red, label="Collar", markershape=:circle, markercolor=:green)
title!("Parábola")
xlabel!("x")
ylabel!("y")

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -2 
 
 
 0 
 
 
 2 
 
 
 0 
 
 
 10 
 
 
 20 
 
 
 Parábola 
 
 
 x 
 
 
 y 
 
<polyline clip-path="url(#clip02)" style="stroke:#ff0000; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 52.8153,33.1822 61.6057,54.5986 70.3961,75.2891 79.1866,95.2535 87.977,114.492 96.7674,133.004 105.558,150.791 114.348,167.852 123.139,184.186 131.929,199.795 
 140.719,214.677 149.51,228.834 158.3,242.265 167.091,254.969 175.881,266.948 184.672,278.201 193.462,288.727 202.252,298.528 211.043,307.603 219.833,315.952 
 228.624,323.574 237.414,330.471 246.204,336.642 254.995,342.087 263.785,346.806 272.576,350.799 281.366,354.066 290.157,356.606 298.947,358.421 307.737,359.51 
 316.528,359.873 325.318,359.51 334.109,358.421 342.899,356.606 351.689,354.066 360.48,350.799 369.27,346.806 378.061,342.087 386.851,336.642 395.642,330.471 
 404.432,323.574 413.222,315.952 422.013,307.603 430.803,298.528 439.594,288.727 448.384,278.201 457.174,266.948 465.965,254.969 474.755,242.265 483.546,228.834 
 492.336,214.677 501.127,199.795 509.917,184.186 518.707,167.852 527.498,150.791 536.288,133.004 545.079,114.492 553.869,95.2535 562.659,75.2891 571.45,54.5986 
 580.24,33.1822 
 "/>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 Collar

In [23]:
# Esta versión organizada se lee mucho mejor... 
plot(x, y, 
    title = "Parábola", 
    xlabel = "Argumento", 
    ylabel = "Imagen", 
    linecolor = :red, 
    markershape = :circle,
    markersize = 5,  # Exploando un poco las opciones
    markercolor = :green,
    label="Collar")

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -2 
 
 
 0 
 
 
 2 
 
 
 0 
 
 
 10 
 
 
 20 
 
 
 Parábola 
 
 
 Argumento 
 
 
 Imagen 
 
<polyline clip-path="url(#clip02)" style="stroke:#ff0000; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 52.8153,33.1822 61.6057,54.5986 70.3961,75.2891 79.1866,95.2535 87.977,114.492 96.7674,133.004 105.558,150.791 114.348,167.852 123.139,184.186 131.929,199.795 
 140.719,214.677 149.51,228.834 158.3,242.265 167.091,254.969 175.881,266.948 184.672,278.201 193.462,288.727 202.252,298.528 211.043,307.603 219.833,315.952 
 228.624,323.574 237.414,330.471 246.204,336.642 254.995,342.087 263.785,346.806 272.576,350.799 281.366,354.066 290.157,356.606 298.947,358.421 307.737,359.51 
 316.528,359.873 325.318,359.51 334.109,358.421 342.899,356.606 351.689,354.066 360.48,350.799 369.27,346.806 378.061,342.087 386.851,336.642 395.642,330.471 
 404.432,323.574 413.222,315.952 422.013,307.603 430.803,298.528 439.594,288.727 448.384,278.201 457.174,266.948 465.965,254.969 474.755,242.265 483.546,228.834 
 492.336,214.677 501.127,199.795 509.917,184.186 518.707,167.852 527.498,150.791 536.288,133.004 545.079,114.492 553.869,95.2535 562.659,75.2891 571.45,54.5986 
 580.24,33.1822 
 "/>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 Collar

## Tiro parabólico

[7] (i) Haz una función que calcula la trayectoria de una partícula en tiro parabólico con una posición y velocidad iniciales dadas.

(ii) Grafica distintas trayectorias con la misma rapidez inicial pero distintos ángulos iniciales. Arregla tu gráfica para que sólo muestra la parte hasta que la partícula caiga al suelo.

(iii) Comprueba gráficamente para cuál ángulo se tiene el máximo **alcance**.

In [24]:
# Separa los argumentos con espacios. Puedes usar acentos si lo prefieres pero no es muy recomendable. 

function tiro_parabolico(v, θ, x0, y0, t_final)   # Aquí se utiliza el ángulo en radianes
    
    tiempos = 0:0.1:t_final
    
    g = 9.81
    vx = v*cos(θ)
    vy = v*sin(θ)
    
    # Una forma aceptable de guardar las posiciones en cada tiempo es utilizar arreglos por comprensión
    X = [vx*t + x0 for t in tiempos]
    Y = [-g*t^2 / 2 + vy*t + y0 for t in tiempos]
    
    return (X,Y)
end

tiro_parabolico (generic function with 1 method)

In [25]:
apropos(max) # Busco una función que me ayude a delimitar mi gráfica.

Base.minmax
Base.gcdx
Base.maxabs
Base.alignment
Base.findmax!
Base.Channel
Base.indmax
Base.big
Base.extrema
Base.length
Base.maximum!
Base.AsyncCollector
Base.maxintfloat
Base.addprocs
Base.max
Base.isapprox
Base.ind2sub
Base.Random.rand
Base.reducedim
Base.IOBuffer
Base.Cintmax_t
Base.retry
Base.LinAlg.pinv
Base.batchsplit
Base.findmax
Base.maxabs!
Base.pmap
Base.reduce
Base.Cuintmax_t
Base.maximum
Base.cummax
Base.split
Base.AsyncGenerator
Base.realmax
Base.read
Base.typemax
Base.PipeBuffer
Base.Threads.atomic_min!
Base.Threads.atomic_max!
Base.Test.@inferred
Base.LinAlg.svds
Base.LinAlg.eigmax
Base.LinAlg.eigs
Base.QuadGK.quadgk
Base.Profile.print
Base.Dates.DateTime
Base.Dates.Date
Base.SparseArrays.sparse
Compat
IJulia.watch_stream
IJulia.set_max_stdio
Base.isapprox
ColorTypes.mapc
Colors
Colors.distinguishable_colors
PlotUtils.adapted_grid
GR.cellarray
GR.setwsviewport
GR.setspace
GR.fillrect
GR.drawimage
GR.fillarc
GR.setwindow
GR.drawarc
GR.drawrect
GR.setwswindow
GR.setviewp

In [26]:
?maximum() # Veo como funciona

```
maximum(itr)
```

Returns the largest element in a collection.

```jldoctest
julia> maximum(-20.5:10)
9.5

julia> maximum([1,2,3])
3
```

```
maximum(A, dims)
```

Compute the maximum value of an array over the given dimensions.


In [27]:
apropos("degrees") # Busco otra función auxiliar.

Base.rotl90
Base.Math.cotd
Base.Math.rad2deg
Base.rotr90
Base.rot180
Base.Math.cscd
Base.Math.secd
Base.Math.deg2rad
Base.Math.cosd
Base.Math.asind
Base.Math.atand
Base.Math.acscd
Base.Math.asecd
Base.Math.acotd
Base.Math.tand
Base.Math.acosd
Base.Math.sind
GR.setspace
GR.fillarc
GR.drawarc


In [28]:
?deg2rad()

```
deg2rad(x)
```

Convert `x` from degrees to radians.


In [29]:
### Primero grafico una trayectoria

## Nombro todas las variables antes de evaluar mi función.

# Busco valores que se vean bien...

t_final = 15
v_inicial = 100

x_inicial = 0
y_inicial = 0

θ_grados = 45                    # Esto representa grados
θ_radianes = deg2rad(θ_grados)  # Esto ya está en radianes

# Guardo los resultados de mi función con nombres (descriptivos) antes de utilizarlos. Así es más claro.

X, Y = tiro_parabolico(v_inicial , θ_radianes, x_inicial, y_inicial, t_final)

x_max = maximum(X)
y_max = maximum(Y)

plot(X, Y,
    title = "Tiro Parabólico", 
    xlabel = "Alcance", 
    ylabel = "Altura", 
    xlims = (0, x_max),       # Podría ser más fino pero por ahora está bien.
    ylim = (0, 1.5 * y_max),  # Sólo la parte hasta que cae al suelo, como dice la instrucción.
    linewidth = 3,
    label = "Ángulo: $θ_grados °   ")  # Intento que todo se vea bien.

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 200 
 
 
 400 
 
 
 600 
 
 
 800 
 
 
 1000 
 
 
 0 
 
 
 100 
 
 
 200 
 
 
 300 
 
 
 Tiro Parabólico 
 
 
 Alcance 
 
 
 Altura 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:2.4; stroke-opacity:1; fill:none" points="
 45.8815,369.674 49.5493,363.313 53.2172,357.04 56.8851,350.857 60.553,344.762 64.2208,338.756 67.8887,332.84 71.5566,327.011 75.2245,321.272 78.8923,315.622 
 82.5602,310.061 86.2281,304.588 89.896,299.204 93.5639,293.909 97.2317,288.703 100.9,283.586 104.567,278.558 108.235,273.619 111.903,268.768 115.571,264.007 
 119.239,259.334 122.907,254.75 126.575,250.255 130.243,245.849 133.91,241.532 137.578,237.303 141.246,233.164 144.914,229.113 148.582,225.151 152.25,221.278 
 155.918,217.494 159.586,213.799 163.254,210.193 166.921,206.675 170.589,203.247 174.257,199.907 177.925,196.656 181.593,193.494 185.261,190.421 188.929,187.437 
 192.597,184.541 196.264,181.735 199.932,179.017 203.6,176.388 207.268,173.849 210.936,171.398 214.604,169.035 218.272,166.762 221.94,164.578 225.607,162.482 
 229.275,160.475 232.943,158.558 236.611,156.729 240.279,154.989 243.947,153.337 247.615,151.775 251.283,150.302 254.95,148.917 258.618,147.621 262.286,146.414 
 265.954,145.296 269.622,144.267 273.29,143.327 276.958,142.476 280.626,141.713 284.293,141.04 287.961,140.455 291.629,139.959 295.297,139.552 298.965,139.234 
 302.633,139.004 306.301,138.864 309.969,138.812 313.636,138.85 317.304,138.976 320.972,139.191 324.64,139.495 328.308,139.888 331.976,140.369 335.644,140.94 
 339.312,141.599 342.979,142.347 346.647,143.185 350.315,144.111 353.983,145.125 357.651,146.229 361.319,147.422 364.987,148.703 368.655,150.074 372.322,151.533 
 375.99,153.081 379.658,154.718 383.326,156.444 386.994,158.258 390.662,160.162 394.33,162.154 397.998,164.236 401.666,166.406 405.333,168.665 409.001,171.013 
 412.669,173.449 416.337,175.975 420.005,178.59 423.673,181.293 427.341,184.085 431.009,186.966 434.676,189.936 438.344,192.995 442.012,196.143 445.68,199.379 
 449.348,202.705 453.016,206.119 456.684,209.622 460.352,213.215 464.019,216.895 467.687,220.665 471.355,224.524 475.023,228.472 478.691,232.508 482.359,236.633 
 486.027,240.847 489.695,245.15 493.362,249.542 497.03,254.023 500.698,258.593 504.366,263.251 508.034,267.999 511.702,272.835 515.37,277.76 519.038,282.774 
 522.705,287.877 526.373,293.068 530.041,298.349 533.709,303.718 537.377,309.177 541.045,314.724 544.713,320.36 548.381,326.085 552.048,331.899 555.716,337.801 
 559.384,343.793 563.052,349.873 566.72,356.043 570.388,362.301 574.056,368.648 577.724,375.084 581.391,381.608 585.059,388.222 588.727,394.924 592.395,401.716 
 596.063,408.596 
 "/>
 
 
 
 
 Ángulo: 45 °

In [30]:
### Ahora dibujo muchas trayectorias en la misma gráfica

t_final = 25
v_inicial = 100   

x_inicial = 0
y_inicial = 0


δθ = 15
θ_min = 10
θ_max = 80

for θ_grados in θ_min : δθ : θ_max
    
    θ_radianes = deg2rad(θ_grados)
    X, Y = tiro_parabolico(v_inicial , θ_radianes, x_inicial, y_inicial, t_final)
    
    plot!(X, Y,
            linewidth = 3,
            label = "Ángulo: $θ_grados °   ")  # Intento que todo se vea bien.
end
title!("Tiros parabólicos")
xlabel!("Alcance")
ylabel!("Altura")
ylims!(0, 500)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 200 
 
 
 400 
 
 
 600 
 
 
 800 
 
 
 1000 
 
 
 0 
 
 
 100 
 
 
 200 
 
 
 300 
 
 
 400 
 
 
 500 
 
 
 Tiros parabólicos 
 
 
 Alcance 
 
 
 Altura 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:2.4; stroke-opacity:1; fill:none" points="
 45.8815,369.674 49.5493,364.811 53.2172,360.015 56.8851,355.288 60.553,350.628 64.2208,346.037 67.8887,341.513 71.5566,337.057 75.2245,332.67 78.8923,328.35 
 82.5602,324.098 86.2281,319.914 89.896,315.798 93.5639,311.75 97.2317,307.77 100.9,303.858 104.567,300.014 108.235,296.237 111.903,292.529 115.571,288.889 
 119.239,285.316 122.907,281.812 126.575,278.375 130.243,275.007 133.91,271.706 137.578,268.473 141.246,265.308 144.914,262.212 148.582,259.183 152.25,256.222 
 155.918,253.329 159.586,250.504 163.254,247.747 166.921,245.057 170.589,242.436 174.257,239.883 177.925,237.397 181.593,234.98 185.261,232.631 188.929,230.349 
 192.597,228.135 196.264,225.99 199.932,223.912 203.6,221.902 207.268,219.961 210.936,218.087 214.604,216.281 218.272,214.543 221.94,212.873 225.607,211.271 
 229.275,209.736 232.943,208.27 236.611,206.872 240.279,205.542 243.947,204.279 247.615,203.085 251.283,201.958 254.95,200.9 258.618,199.909 262.286,198.986 
 265.954,198.132 269.622,197.345 273.29,196.626 276.958,195.975 280.626,195.392 284.293,194.877 287.961,194.43 291.629,194.051 295.297,193.74 298.965,193.497 
 302.633,193.321 306.301,193.214 309.969,193.174 313.636,193.203 317.304,193.299 320.972,193.464 324.64,193.696 328.308,193.997 331.976,194.365 335.644,194.801 
 339.312,195.305 342.979,195.877 346.647,196.517 350.315,197.225 353.983,198.001 357.651,198.845 361.319,199.757 364.987,200.736 368.655,201.784 372.322,202.9 
 375.99,204.083 379.658,205.335 383.326,206.654 386.994,208.041 390.662,209.497 394.33,211.02 397.998,212.611 401.666,214.27 405.333,215.997 409.001,217.792 
 412.669,219.655 416.337,221.586 420.005,223.585 423.673,225.652 427.341,227.787 431.009,229.989 434.676,232.26 438.344,234.599 442.012,237.005 445.68,239.48 
 449.348,242.022 453.016,244.632 456.684,247.311 460.352,250.057 464.019,252.871 467.687,255.753 471.355,258.703 475.023,261.721 478.691,264.807 482.359,267.961 
 486.027,271.183 489.695,274.473 493.362,277.83 497.03,281.256 500.698,284.75 504.366,288.311 508.034,291.941 511.702,295.638 515.37,299.403 519.038,303.237 
 522.705,307.138 526.373,311.107 530.041,315.144 533.709,319.249 537.377,323.422 541.045,327.663 544.713,331.972 548.381,336.349 552.048,340.794 555.716,345.307 
 559.384,349.887 563.052,354.536 566.72,359.252 570.388,364.037 574.056,368.889 577.724,373.81 581.391,378.798 585.059,383.854 588.727,388.979 592.395,394.171 
 596.063,399.431 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#e9746a; stroke-width:2.4; stroke-opacity:1; fill:none" points="
 45.8815,369.674 50.9898,368.505 56.0982,367.405 61.2065,366.372 66.3149,365.407 71.4232,364.51 76.5316,363.681 81.6399,362.92 86.7483,362.227 91.8567,361.602 
 96.965,361.045 102.073,360.555 107.182,360.134 112.29,359.781 117.398,359.495 122.507,359.278 127.615,359.128 132.724,359.047 137.832,359.033 142.94,359.087 
 148.049,359.209 153.157,359.4 158.265,359.658 163.374,359.984 168.482,360.378 173.59,360.84 178.699,361.37 183.807,361.967 188.915,362.633 194.024,363.367 
 199.132,364.168 204.241,365.038 209.349,365.976 214.457,366.981 219.566,368.054 224.674,369.196 229.782,370.405 234.891,371.682 239.999,373.028 245.107,374.441 
 250.216,375.922 255.324,377.471 260.432,379.088 265.541,380.773 270.649,382.525 275.758,384.346 280.866,386.235 285.974,388.192 291.083,390.216 296.191,392.309 
 301.299,394.469 306.408,396.698 311.516,398.994 316.624,401.358 321.733,403.791 326.841,406.291 331.949,408.859 337.058,411.495 342.166,414.199 347.274,416.971 
 352.383,419.811 357.491,422.719 362.6,425.695 367.708,428.739 372.816,431.85 377.925,435.03 383.033

* Claramente el máximo alcance se obtiene cuando el ángulo inicial es $\pi/4$.

## Calculando $\pi$

Ya estamos llegando a poder hacer cálculos útiles:

[8] Una manera de calcular $\pi$ es al utilizar la [siguiente fórmula](https://en.wikipedia.org/wiki/Basel_problem):

$$\sum_{n=1}^\infty \frac{1}{n^2} = \frac{\pi^2}{6}.$$

* Voy a separar lo incisos para que se entienda mejor mi tarea. Con `<Ctrl-Shift-Minus>` es fácil hacerlo.

(i) Fija una $N$ y calcula $\pi$ usando una suma hasta $N$. Haz de esto una función que se llama `mi_π`.
["π" se teclea como `\pi<TAB>`.]

In [31]:
function mi_π(n)  # Separo las operaciones con nombres descriptivos para que se lea facilmente mi código.
    elementos_suma = [1/(i^2) for i in 1:n]
    suma = sum(elementos_suma)
    return sqrt(6*suma)
end

mi_π (generic function with 1 method)

(ii) Ahora repite el cálculo para valores diferentes de $N$, *usando sólo lo que hemos visto en este notebook*.

In [32]:
aproximaciones = [mi_π(i) for i in 1:10:100] 

10-element Array{Float64,1}:
 2.44949
 3.05748
 3.09687
 3.11113
 3.1185 
 3.123  
 3.12603
 3.12821
 3.12985
 3.13114

(iii) Grafica el resultado para los distintos valores de $N$, como función de $N$. ¿Qué observas? ¿Qué puedes agregar a tu gráfica para mostralo?

In [33]:
# Si defino todo en una función podré experimentar más fácilmente.

function aprox_pi(N)
    
    rango = 0:10:N
    aproximaciones = [mi_π(i) for i in rango] 
    
    plot( rango, aproximaciones,
            linewidth=3,
            xlabel="N",
            ylabel="mi_pi",
            title="Calculando Pi",
            label="Mi función",
            ylims=(3.0,3.15) )
    hline!([π],linewidth=3,label="Valor de Pi")
end

aprox_pi (generic function with 1 method)

In [34]:
aprox_pi(1000)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 200 
 
 
 400 
 
 
 600 
 
 
 800 
 
 
 1000 
 
 
 3.00 
 
 
 3.05 
 
 
 3.10 
 
 
 Calculando Pi 
 
 
 N 
 
 
 mi 
 
 
 pi 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:2.4; stroke-opacity:1; fill:none" points="
 54.7703,7295.53 60.1833,255.717 65.5962,151.118 71.0091,115.429 76.422,97.4276 81.835,86.5763 87.2479,79.3211 92.6608,74.1284 98.0738,70.2283 103.487,67.1915 
 108.9,64.7599 114.313,62.769 119.725,61.109 125.138,59.7037 130.551,58.4986 135.964,57.4539 141.377,56.5394 146.79,55.7323 152.203,55.0147 157.616,54.3726 
 163.029,53.7945 168.442,53.2714 173.855,52.7957 179.268,52.3614 184.681,51.9632 190.094,51.5968 195.506,51.2586 200.919,50.9453 206.332,50.6545 211.745,50.3836 
 217.158,50.1308 222.571,49.8943 227.984,49.6726 233.397,49.4643 238.81,49.2682 244.223,49.0833 249.636,48.9087 255.049,48.7435 260.462,48.587 265.874,48.4385 
 271.287,48.2974 276.7,48.1632 282.113,48.0354 287.526,47.9136 292.939,47.7972 298.352,47.6861 303.765,47.5797 309.178,47.4779 314.591,47.3803 320.004,47.2867 
 325.417,47.1969 330.83,47.1105 336.243,47.0275 341.655,46.9476 347.068,46.8707 352.481,46.7966 357.894,46.7251 363.307,46.6561 368.72,46.5895 374.133,46.5252 
 379.546,46.4629 384.959,46.4028 390.372,46.3446 395.785,46.2882 401.198,46.2336 406.611,46.1806 412.023,46.1293 417.436,46.0795 422.849,46.0312 428.262,45.9842 
 433.675,45.9386 439.088,45.8943 444.501,45.8512 449.914,45.8093 455.327,45.7685 460.74,45.7289 466.153,45.6902 471.566,45.6526 476.979,45.6159 482.392,45.5802 
 487.804,45.5453 493.217,45.5113 498.63,45.4782 504.043,45.4458 509.456,45.4142 514.869,45.3833 520.282,45.3532 525.695,45.3238 531.108,45.295 536.521,45.2669 
 541.934,45.2394 547.347,45.2125 552.76,45.1862 558.173,45.1604 563.585,45.1352 568.998,45.1105 574.411,45.0864 579.824,45.0627 585.237,45.0396 590.65,45.0169 
 596.063,44.9946 
 "/>
 
 
 
 
 
 Mi función 
 
 
 
 Valor de Pi

(iv) ¿Cómo podrías ver qué tan rápidamente converge la suma cuando $N \to \infty$? Hazlo.

In [35]:
# Analizando el valor absoluto de la diferencia entre mi aproximación y el valor real en función de N.

function convergencia_pi(N)
    
    rango = 1:10:N
    separacion = [abs(mi_π(i) - π ) for i in rango]
    
    plot(rango, separacion,
        linecolor = :blue, 
        markershape = :circle,
        markersize = 5,  # Exploando un poco las opciones
        markercolor = :magenta,
        alpha = 0.5,
        xscale = :log10, 
        yscale = :log10,
        label = "Aproximaciones   ",
        xlabel = "Orden de aproximación",
        ylabel = "Diferencia con valor real",
        title = "Convergencia a Pi")

end

convergencia_pi (generic function with 1 method)

In [36]:
convergencia_pi(100)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 10 
 
 
 0.0 
 
 
 10 
 
 
 0.5 
 
 
 10 
 
 
 1.0 
 
 
 10 
 
 
 1.5 
 
 
 10 
 
 
 - 
 
 
 1.5 
 
 
 10 
 
 
 - 
 
 
 1.0 
 
 
 10 
 
 
 - 
 
 
 0.5 
 
 
 Convergencia a Pi 
 
 
 Orden de aproximación 
 
 
 Diferencia con valor real 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 Aproximaciones

La gráfica con ejes logarítmicos es una linea recta.

Si $\Delta$ representa la diferencia entre el valor real y mi aproximación, $b$ la ordenada al origen y $m$ la pendiente de la recta obtenida, tenemos que:

$$ log_{10}\Delta = b + m \log_{10}N$$ 

$$ \Delta = 10^{ b + m \log_{10}N} = 10^b N^m $$

In [37]:
?linreg  # Usamos lo que se mostró en clase.

search: linreg linearindices LineNumberNode



```
linreg(x, y)
```

Perform simple linear regression using Ordinary Least Squares. Returns `a` and `b` such that `a + b*x` is the closest straight line to the given points `(x, y)`, i.e., such that the squared error between `y` and `a + b*x` is minimized.

Examples:

```
using PyPlot
x = 1.0:12.0
y = [5.5, 6.3, 7.6, 8.8, 10.9, 11.79, 13.48, 15.02, 17.77, 20.81, 22.0, 22.99]
a, b = linreg(x, y)          # Linear regression
plot(x, y, "o")              # Plot (x, y) points
plot(x, a + b*x)             # Plot line determined by linear regression
```

See also:

`\`, `cov`, `std`, `mean`


In [38]:
rango = 1:10:10000
separacion = [abs(mi_π(i) - π ) for i in rango]
b, m = linreg(log(rango), log(separacion))

(-0.0730631287552459,-0.9967867713271358)

$$ \Delta \sim \frac{1}{N} $$